language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      brew_packages: protobuf
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      warnings_are_errors: false
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    update: true
    packages:
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
