language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: protobuf
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      warnings_are_errors: false
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    update: true
    packages:
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
